import 'dart:io';
import 'package:openbao_api/openbao_api.dart' as api;
import '../models/deploy_config.dart';
import '../utils/console.dart';
import '../utils/config_paths.dart';
import 'token_storage.dart';

class OpenBaoService {
  final String address;
  final OpenBaoConfig? config;
  Environment _currentEnv;

  OpenBaoService({
    required this.address,
    this.config,
    Environment environment = Environment.local,
  }) : _currentEnv = environment;

  /// Set the current environment
  set currentEnvironment(Environment env) => _currentEnv = env;

  /// Get token manager path for current environment
  String? get tokenManager => config?.getTokenManager(_currentEnv);

  /// Get policy for current environment
  String? get policy => config?.getPolicy(_currentEnv);

  /// Get role_id for current environment
  String? get roleId => config?.getEnvConfig(_currentEnv)?.roleId;

  /// Get role_name for current environment
  String? get roleName => config?.getEnvConfig(_currentEnv)?.roleName;

  /// Get secret path for current environment
  String? get secretPath => config?.getSecretPath(_currentEnv);

  /// Check if a string looks like a file path
  bool _isFilePath(String value) {
    return value.startsWith('/') ||
        value.startsWith('~/') ||
        value.startsWith('./') ||
        value.startsWith('../') ||
        value.contains('/') ||
        value.contains('\\');
  }

  api.OpenBaoClient _getClient() {
    String? mgrToken = tokenManager;
    if (mgrToken != null && _isFilePath(mgrToken)) {
      mgrToken = ConfigPaths.expandPath(mgrToken);
    }

    return api.OpenBaoClient(
      address: address,
      tokenStorage: TokenStorage.instance.apiStorage,
      roleId: roleId,
      roleName: roleName,
      managerToken: mgrToken,
    );
  }

  /// Ensure we have a valid token
  Future<bool> createToken() async {
    try {
      Console.info('Checking authentication for ${_currentEnv.name}...');
      await _getClient().getOrCreateToken(_currentEnv.name);
      Console.success('Authentication successful for ${_currentEnv.name}');
      return true;
    } catch (e) {
      Console.error('Failed to authenticate: $e');
      return false;
    }
  }

  Future<Map<String, String>> fetchSecrets(String secretPath) async {
    Console.info('Fetching secrets from OpenBao: $secretPath');

    try {
      return await _getClient().fetchSecrets(secretPath, _currentEnv.name);
    } catch (e) {
      if (e is api.OpenBaoException) {
        throw Exception(e.message);
      }
      throw Exception('Failed to fetch secrets: $e');
    }
  }

  Future<void> writeEnvFile(String secretPath, String envFilePath) async {
    final secrets = await fetchSecrets(secretPath);

    final buffer = StringBuffer();
    buffer.writeln('# Generated by dart_cloud_deploy from OpenBao');
    buffer.writeln('# Path: $secretPath');
    buffer.writeln('# Generated at: ${DateTime.now().toIso8601String()}');
    buffer.writeln('');

    for (final entry in secrets.entries) {
      final value = entry.value;
      // Quote values that contain spaces or special characters
      if (value.contains(' ') || value.contains('"') || value.contains("'")) {
        buffer.writeln('${entry.key}="${value.replaceAll('"', '\\"')}"');
      } else {
        buffer.writeln('${entry.key}=$value');
      }
    }

    final file = File(envFilePath);
    await file.writeAsString(buffer.toString());

    // Set restrictive permissions
    if (!Platform.isWindows) {
      await Process.run('chmod', ['600', envFilePath]);
    }

    Console.success(
      'Secrets written to $envFilePath (${secrets.length} variables)',
    );
  }

  Future<List<String>> listSecrets(String path) async {
    try {
      return await _getClient().listSecrets(path, _currentEnv.name);
    } catch (e) {
      Console.warning('Failed to list secrets at $path: $e');
      return [];
    }
  }

  Future<bool> checkHealth() async {
    return _getClient().checkHealth();
  }
}
