import 'dart:io';
import 'package:openbao_api/openbao_api.dart' as api;
import '../models/deploy_config.dart';
import '../utils/console.dart';
import '../utils/config_paths.dart';
import 'token_storage.dart';

class OpenBaoService {
  final OpenBaoConfig config;
  final Environment environment;

  OpenBaoService({
    required this.config,
    required this.environment,
  });

  /// Get address
  String get address => config.address;

  /// Get token manager path
  String get tokenManager => config.tokenManager;

  /// Get policy
  String get policy => config.policy;

  /// Get role_id
  String get roleId => config.roleId;

  /// Get role_name
  String get roleName => config.roleName;

  /// Get secret path
  String get secretPath => config.secretPath;

  /// Check if a string looks like a file path
  bool _isFilePath(String value) {
    return value.startsWith('/') ||
        value.startsWith('~/') ||
        value.startsWith('./') ||
        value.startsWith('../') ||
        value.contains('/') ||
        value.contains('\\');
  }

  api.OpenBaoClient _getClient() {
    String mgrToken = tokenManager;
    if (_isFilePath(mgrToken)) {
      mgrToken = ConfigPaths.expandPath(mgrToken);
    }

    return api.OpenBaoClient(
      address: address,
      tokenStorage: TokenStorage.instance.apiStorage,
      roleId: roleId,
      roleName: roleName,
      managerToken: mgrToken,
    );
  }

  /// Ensure we have a valid token
  Future<bool> createToken() async {
    try {
      Console.info('Checking authentication for ${environment.name}...');
      await _getClient().getOrCreateToken(environment.name);
      Console.success('Authentication successful for ${environment.name}');
      return true;
    } catch (e) {
      Console.error('Failed to authenticate: $e');
      return false;
    }
  }

  Future<Map<String, String>> fetchSecrets(String secretPath) async {
    Console.info('Fetching secrets from OpenBao: $secretPath');

    try {
      final client = _getClient();
      return client.fetchSecrets(secretPath, environment.name);
    } catch (e) {
      if (e is api.OpenBaoException) {
        throw Exception(e.message);
      }
      throw Exception('Failed to fetch secrets: $e');
    }
  }

  Future<void> writeEnvFile(String secretPath, String envFilePath) async {
    final secrets = await fetchSecrets(secretPath);

    final buffer = StringBuffer();
    buffer.writeln('# Generated by dart_cloud_deploy from OpenBao');
    buffer.writeln('# Path: $secretPath');
    buffer.writeln('# Generated at: ${DateTime.now().toIso8601String()}');
    buffer.writeln('');

    for (final entry in secrets.entries) {
      final value = entry.value;
      // Quote values that contain spaces or special characters
      if (value.contains(' ') || value.contains('"') || value.contains("'")) {
        buffer.writeln('${entry.key}="${value.replaceAll('"', '\\"')}"');
      } else {
        buffer.writeln('${entry.key}=$value');
      }
    }

    final file = File(envFilePath);
    await file.writeAsString(buffer.toString());

    // Set restrictive permissions
    if (!Platform.isWindows) {
      await Process.run('chmod', ['600', envFilePath]);
    }

    Console.success(
      'Secrets written to $envFilePath (${secrets.length} variables)',
    );
  }

  Future<List<String>> listSecrets(String path) async {
    try {
      return await _getClient().listSecrets(path, environment.name);
    } catch (e) {
      Console.warning('Failed to list secrets at $path: $e');
      return [];
    }
  }

  Future<bool> checkHealth() async {
    return _getClient().checkHealth();
  }
}
